//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XInputPlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XInputPlus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_x64 {
            get {
                object obj = ResourceManager.GetObject("xinput1_x64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_x86 {
            get {
                object obj = ResourceManager.GetObject("xinput1_x86", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [General]
        ///iniFileVersion=4150
        ///[KeyAssign]
        ///LS=LS
        ///RS=RS
        ///LT=LT
        ///RT=RT
        ///DPAD_UP=DPAD_UP
        ///DPAD_DOWN=DPAD_DOWN
        ///DPAD_LEFT=DPAD_LEFT
        ///DPAD_RIGHT=DPAD_RIGHT
        ///A=A
        ///B=B
        ///X=X
        ///Y=Y
        ///LB=LB
        ///RB=RB
        ///LSB=LSB
        ///RSB=RSB
        ///BACK=BACK
        ///START=START
        ///GUIDE=GUIDE
        ///ThresholdA2D=40
        ///DPAD4Direction=False
        ///[LeftStick]
        ///DeadZone=0
        ///Saturation=32767
        ///Linearity=1
        ///Response=32767
        ///RectCorrection=0
        ///Scale=1
        ///CenterOffsetX=0
        ///CenterOffsetY=0
        ///InvertX=False
        ///InvertY=False
        ///DisableX=False
        ///DisableY=False
        ///[RightStick]
        ///DeadZone=0
        ///Saturati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XInputPlus {
            get {
                return ResourceManager.GetString("XInputPlus", resourceCulture);
            }
        }
    }
}
